/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichTextBlock = {
  _type: "richTextBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type FaqBlock = {
  _type: "faqBlock";
  title?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type LogoCloudBlock = {
  _type: "logoCloudBlock";
  title?: string;
  logos?: Array<{
    name?: string;
    image?: ImageWithAlt;
    url?: string;
    _key: string;
  }>;
};

export type TestimonialBlock = {
  _type: "testimonialBlock";
  quote?: string;
  avatar?: ImageWithAlt;
  name?: string;
  role?: string;
};

export type FullWidthMediaBlock = {
  _type: "fullWidthMediaBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  action?: Link;
  background?: "plain" | "brand" | "dark";
  textAlign?: "left" | "center" | "right";
};

export type GalleryBlock = {
  _type: "galleryBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
};

export type ImageTextBlock = {
  _type: "imageTextBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  action?: Link;
  imagePosition?: "left" | "right";
};

export type FeatureGridBlock = {
  _type: "featureGridBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  features?: Array<{
    title?: string;
    body?: string;
    image?: ImageWithAlt;
    _key: string;
  }>;
};

export type CtaBlock = {
  _type: "ctaBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  primaryAction?: Link;
  secondaryAction?: Link;
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  cta?: Link;
  layout?: "textOnly" | "imageRight" | "imageLeft" | "backgroundImage";
  textAlign?: "left" | "center" | "right";
  verticalAlign?: "top" | "center" | "bottom";
  typographyScale?: "standard" | "large" | "editorial";
  backgroundStyle?: "dark" | "light" | "brand" | "gradient";
  verticalSpacing?: "compact" | "standard" | "tall" | "fullViewport";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  noIndex?: boolean;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  page?: PageReference;
  href?: string;
  openInNewTab?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logoText?: string;
  primaryNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
  footerNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  blocks?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & FeatureGridBlock)
    | ({
        _key: string;
      } & ImageTextBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & FullWidthMediaBlock)
    | ({
        _key: string;
      } & TestimonialBlock)
    | ({
        _key: string;
      } & LogoCloudBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & RichTextBlock)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichTextBlock
  | FaqBlock
  | LogoCloudBlock
  | TestimonialBlock
  | FullWidthMediaBlock
  | GalleryBlock
  | ImageTextBlock
  | FeatureGridBlock
  | CtaBlock
  | HeroBlock
  | SanityImageAssetReference
  | ImageWithAlt
  | Seo
  | PageReference
  | Link
  | SiteSettings
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
