/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichTextBlock = {
  _type: "richTextBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type FaqBlock = {
  _type: "faqBlock";
  title?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type LogoCloudBlock = {
  _type: "logoCloudBlock";
  title?: string;
  logos?: Array<{
    name?: string;
    image?: ImageWithAlt;
    url?: string;
    _key: string;
  }>;
};

export type TestimonialBlock = {
  _type: "testimonialBlock";
  quote?: string;
  avatar?: ImageWithAlt;
  name?: string;
  role?: string;
};

export type FullWidthMediaBlock = {
  _type: "fullWidthMediaBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  action?: Link;
  background?: "plain" | "brand" | "dark";
  textAlign?: "left" | "center" | "right";
};

export type GalleryBlock = {
  _type: "galleryBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
};

export type ImageTextBlock = {
  _type: "imageTextBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  action?: Link;
  imagePosition?: "left" | "right";
};

export type FeatureGridBlock = {
  _type: "featureGridBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  features?: Array<{
    title?: string;
    body?: string;
    image?: ImageWithAlt;
    _key: string;
  }>;
};

export type CtaBlock = {
  _type: "ctaBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  primaryAction?: Link;
  secondaryAction?: Link;
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  title?: string;
  body?: string;
  image?: ImageWithAlt;
  cta?: Link;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  noIndex?: boolean;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  page?: PageReference;
  href?: string;
  openInNewTab?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logoText?: string;
  primaryNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
  footerNavigation?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  blocks?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & CtaBlock)
    | ({
        _key: string;
      } & FeatureGridBlock)
    | ({
        _key: string;
      } & ImageTextBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & FullWidthMediaBlock)
    | ({
        _key: string;
      } & TestimonialBlock)
    | ({
        _key: string;
      } & LogoCloudBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & RichTextBlock)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichTextBlock
  | FaqBlock
  | LogoCloudBlock
  | TestimonialBlock
  | FullWidthMediaBlock
  | GalleryBlock
  | ImageTextBlock
  | FeatureGridBlock
  | CtaBlock
  | HeroBlock
  | SanityImageAssetReference
  | ImageWithAlt
  | Seo
  | PageReference
  | Link
  | SiteSettings
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../../packages/cms/src/queries/index.ts
// Variable: imageFields
// Query: {  ...,  asset->{    _id,    metadata{      dimensions{        aspectRatio,        height,        width      },      lqip    }  }}
export type ImageFieldsResult = never;

// Source: ../../packages/cms/src/queries/index.ts
// Variable: linkFields
// Query: {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )}
export type LinkFieldsResult = {
  label: never;
  openInNewTab: never;
  href: never;
};

// Source: ../../packages/cms/src/queries/index.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  title,  "slug": slug.current,  seo,  blocks[]{    ...,    cta {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )},    primaryAction {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )},    secondaryAction {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )},    action {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )},    image {  ...,  asset->{    _id,    metadata{      dimensions{        aspectRatio,        height,        width      },      lqip    }  }},    avatar {  ...,  asset->{    _id,    metadata{      dimensions{        aspectRatio,        height,        width      },      lqip    }  }},    features[]{      ...,      image {  ...,  asset->{    _id,    metadata{      dimensions{        aspectRatio,        height,        width      },      lqip    }  }}    },    images[] {  ...,  asset->{    _id,    metadata{      dimensions{        aspectRatio,        height,        width      },      lqip    }  }},    logos[]{      ...,      image {  ...,  asset->{    _id,    metadata{      dimensions{        aspectRatio,        height,        width      },      lqip    }  }}    }  }}
export type PageBySlugQueryResult = {
  title: string | null;
  slug: string | null;
  seo: Seo | null;
  blocks: Array<
    | {
        _key: string;
        _type: "ctaBlock";
        eyebrow?: string;
        title?: string;
        body?: string;
        primaryAction: {
          label: string | null;
          openInNewTab: boolean | null;
          href: string | "/" | null;
        } | null;
        secondaryAction: {
          label: string | null;
          openInNewTab: boolean | null;
          href: string | "/" | null;
        } | null;
        cta: null;
        action: null;
        image: null;
        avatar: null;
        features: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "faqBlock";
        title?: string;
        items?: Array<{
          question?: string;
          answer?: string;
          _key: string;
        }>;
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        image: null;
        avatar: null;
        features: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "featureGridBlock";
        eyebrow?: string;
        title?: string;
        body?: string;
        features: Array<{
          title?: string;
          body?: string;
          image: {
            _type: "imageWithAlt";
            asset: {
              _id: string;
              metadata: {
                dimensions: {
                  aspectRatio: number | null;
                  height: number | null;
                  width: number | null;
                } | null;
                lqip: string | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
          } | null;
          _key: string;
        }> | null;
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        image: null;
        avatar: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "fullWidthMediaBlock";
        eyebrow?: string;
        title?: string;
        body?: string;
        image: {
          _type: "imageWithAlt";
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                aspectRatio: number | null;
                height: number | null;
                width: number | null;
              } | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
        } | null;
        action: {
          label: string | null;
          openInNewTab: boolean | null;
          href: string | "/" | null;
        } | null;
        background?: "brand" | "dark" | "plain";
        textAlign?: "center" | "left" | "right";
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        avatar: null;
        features: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "galleryBlock";
        eyebrow?: string;
        title?: string;
        body?: string;
        images: Array<{
          _key: string;
          _type: "imageWithAlt";
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                aspectRatio: number | null;
                height: number | null;
                width: number | null;
              } | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
        }> | null;
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        image: null;
        avatar: null;
        features: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "heroBlock";
        eyebrow?: string;
        title?: string;
        body?: string;
        image: {
          _type: "imageWithAlt";
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                aspectRatio: number | null;
                height: number | null;
                width: number | null;
              } | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
        } | null;
        cta: {
          label: string | null;
          openInNewTab: boolean | null;
          href: string | "/" | null;
        } | null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        avatar: null;
        features: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "imageTextBlock";
        eyebrow?: string;
        title?: string;
        body?: string;
        image: {
          _type: "imageWithAlt";
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                aspectRatio: number | null;
                height: number | null;
                width: number | null;
              } | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
        } | null;
        action: {
          label: string | null;
          openInNewTab: boolean | null;
          href: string | "/" | null;
        } | null;
        imagePosition?: "left" | "right";
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        avatar: null;
        features: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "logoCloudBlock";
        title?: string;
        logos: Array<{
          name?: string;
          image: {
            _type: "imageWithAlt";
            asset: {
              _id: string;
              metadata: {
                dimensions: {
                  aspectRatio: number | null;
                  height: number | null;
                  width: number | null;
                } | null;
                lqip: string | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            caption?: string;
          } | null;
          url?: string;
          _key: string;
        }> | null;
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        image: null;
        avatar: null;
        features: null;
        images: null;
      }
    | {
        _key: string;
        _type: "richTextBlock";
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        image: null;
        avatar: null;
        features: null;
        images: null;
        logos: null;
      }
    | {
        _key: string;
        _type: "testimonialBlock";
        quote?: string;
        avatar: {
          _type: "imageWithAlt";
          asset: {
            _id: string;
            metadata: {
              dimensions: {
                aspectRatio: number | null;
                height: number | null;
                width: number | null;
              } | null;
              lqip: string | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
        } | null;
        name?: string;
        role?: string;
        cta: null;
        primaryAction: null;
        secondaryAction: null;
        action: null;
        image: null;
        features: null;
        images: null;
        logos: null;
      }
  > | null;
} | null;

// Source: ../../packages/cms/src/queries/index.ts
// Variable: allPageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)][]{  "slug": slug.current}
export type AllPageSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: ../../packages/cms/src/queries/index.ts
// Variable: sitemapPagesQuery
// Query: *[_type == "page" && defined(slug.current) && seo.noIndex != true]{  _updatedAt,  "slug": slug.current}
export type SitemapPagesQueryResult = Array<{
  _updatedAt: string;
  slug: string | null;
}>;

// Source: ../../packages/cms/src/queries/index.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  title,  description,  logoText,  primaryNavigation[] {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )},  footerNavigation[] {  label,  openInNewTab,  "href": select(    page->slug.current == "home" => "/",    defined(page->slug.current) => "/" + page->slug.current,    href  )}}
export type SiteSettingsQueryResult = {
  title: string | null;
  description: string | null;
  logoText: string | null;
  primaryNavigation: Array<{
    label: string | null;
    openInNewTab: boolean | null;
    href: string | "/" | null;
  }> | null;
  footerNavigation: Array<{
    label: string | null;
    openInNewTab: boolean | null;
    href: string | "/" | null;
  }> | null;
} | null;

